// mock.ts
import type { ClientListItem } from "@/entities";

export const MOCK_CLIENTS: Record<
	"active" | "expired" | "expiring",
	ClientListItem[]
> = {
	active: [
		{
			id: 1,
			companyName: "ООО Ромашка",
			level: "LEVEL_3",
			licensesTotal: 5,
			licensesActive: 3,
			licensesNotActive: 2,
			licensesExpired: 0,
			daysLeftNearest: 15,
			tgUsername: "@romashka_business",
			tgLink: "https://t.me/romashka_business",
			isExpiringSoon: false,
			isFullyExpired: false,
		},
		{
			id: 2,
			companyName: "ИП Иванов",
			level: "LEVEL_4",
			licensesTotal: 10,
			licensesActive: 8,
			licensesNotActive: 2,
			licensesExpired: 0,
			daysLeftNearest: 45,
			tgUsername: "@ivanov_co",
			tgLink: "https://t.me/ivanov_co",
			isExpiringSoon: false,
			isFullyExpired: false,
		},
		{
			id: 3,
			companyName: "ОАО ТехноПро",
			level: "LEVEL_3",
			licensesTotal: 3,
			licensesActive: 3,
			licensesNotActive: 0,
			licensesExpired: 0,
			daysLeftNearest: 3,
			tgUsername: "@technopro",
			tgLink: "https://t.me/technopro",
			isExpiringSoon: true,
			isFullyExpired: false,
		},
	],
	expired: [
		{
			id: 4,
			companyName: "ООО СтартАп",
			level: "LEVEL_3",
			licensesTotal: 2,
			licensesActive: 0,
			licensesNotActive: 0,
			licensesExpired: 2,
			daysLeftNearest: -5,
			tgUsername: "@startup_llc",
			tgLink: "https://t.me/startup_llc",
			isExpiringSoon: false,
			isFullyExpired: true,
		},
		{
			id: 5,
			companyName: "ИП Петров",
			level: "LEVEL_4",
			licensesTotal: 5,
			licensesActive: 0,
			licensesNotActive: 0,
			licensesExpired: 5,
			daysLeftNearest: -15,
			tgUsername: "@petrov_business",
			tgLink: "https://t.me/petrov_business",
			isExpiringSoon: false,
			isFullyExpired: true,
		},
	],
	expiring: [
		{
			id: 6,
			companyName: "ООО Будущее",
			level: "LEVEL_3",
			licensesTotal: 4,
			licensesActive: 4,
			licensesNotActive: 0,
			licensesExpired: 0,
			daysLeftNearest: 2,
			tgUsername: "@future_llc",
			tgLink: "https://t.me/future_llc",
			isExpiringSoon: true,
			isFullyExpired: false,
		},
		{
			id: 7,
			companyName: "ИП Сидоров",
			level: "LEVEL_4",
			licensesTotal: 7,
			licensesActive: 5,
			licensesNotActive: 2,
			licensesExpired: 0,
			daysLeftNearest: 5,
			tgUsername: "@sidorov_trade",
			tgLink: "https://t.me/sidorov_trade",
			isExpiringSoon: true,
			isFullyExpired: false,
		},
		{
			id: 3,
			companyName: "ОАО ТехноПро",
			level: "LEVEL_3",
			licensesTotal: 3,
			licensesActive: 3,
			licensesNotActive: 0,
			licensesExpired: 0,
			daysLeftNearest: 3,
			tgUsername: "@technopro",
			tgLink: "https://t.me/technopro",
			isExpiringSoon: true,
			isFullyExpired: false,
		},
	],
};
